name: emissor_nfe
description: App Flutter do Emissor de NF-e multi-tenant (consome a API Laravel/sped-nfe).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.0   # persiste o token da sessão
  file_picker: ^8.0.0          # seleção do .pfx no upload de certificado

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
